steps:
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'version']
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'test']
  dir: 'go/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'go-test', '--trigger-http', '--runtime', 'go113', '--entry-point', 'Decode']
  dir: 'go/'
